# Generated by Django 3.0.7 on 2020-06-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=60)),
                ('Course_Number', models.IntegerField(blank=True, default=0)),
                ('Instructor_Name', models.CharField(blank=True, default='', max_length=100)),
                ('Duration', models.FloatField(blank=True, null=True)),
                ('Test', models.FloatField()),
            ],
        ),
    ]
