# Generated by Django 2.2.5 on 2020-05-27 19:26

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TexasGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_loss', models.CharField(choices=[('Texas', 'Texas'), ('Opponent', 'Opponent')], max_length=20)),
                ('stadium', models.CharField(choices=[('Home', 'Home'), ('Away', 'Away'), ('Other', 'Other')], max_length=20)),
                ('against', models.CharField(choices=[('South Florida', 'South Florida'), ('Louisiana State University', 'Louisiana State University'), ('Kansas State', 'Kansas State'), ('Oklahoma State', 'Oklahoma State'), ('Oklahoma', 'Oklahoma'), ('West Virginia', 'West Virginia'), ('Texas Tech', 'Texas Tech'), ('Baylor', 'Baylor'), ('Kansas', 'Kansas'), ('Iowa State', 'Iowa State'), ('Texas Christian University', 'Texas Christian University'), ('Other', 'Other')], max_length=20)),
                ('time_of_day', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening'), ('Other', 'Other')], max_length=20)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('significance', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=20)),
            ],
            managers=[
                ('TexasGames', django.db.models.manager.Manager()),
            ],
        ),
    ]
