# Generated by Django 2.2.5 on 2020-05-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TexasScore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texasgame',
            name='against',
            field=models.CharField(choices=[('South Florida', 'South Florida'), ('Louisiana State University', 'Louisiana State University'), ('Kansas State', 'Kansas State'), ('Oklahoma State', 'Oklahoma State'), ('Oklahoma', 'Oklahoma'), ('West Virginia', 'West Virginia'), ('Texas Tech', 'Texas Tech'), ('Baylor', 'Baylor'), ('Kansas', 'Kansas'), ('Iowa State', 'Iowa State'), ('Texas Christian University', 'Texas Christian University'), ('Other', 'Other')], max_length=75),
        ),
    ]
