# Generated by Django 2.2.5 on 2020-06-01 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games_UpComing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_Name', models.CharField(max_length=250, verbose_name='Game Name')),
                ('Release', models.CharField(max_length=250, verbose_name='Potential Release')),
                ('Main_Console', models.CharField(max_length=250, verbose_name='Main Console')),
                ('Sources', models.CharField(max_length=250, verbose_name='Spy Sources')),
            ],
        ),
        migrations.DeleteModel(
            name='GCollection',
        ),
    ]
