# Generated by Django 2.2.5 on 2020-06-03 23:42

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0002_auto_20200531_2146'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='games_upcoming',
            managers=[
                ('eventModel', django.db.models.manager.Manager()),
            ],
        ),
    ]
