# Generated by Django 2.2.5 on 2020-06-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(blank=True, default='', max_length=100)),
                ('game_designer', models.CharField(blank=True, default='', max_length=100)),
                ('game_publisher', models.CharField(blank=True, default='', max_length=100)),
                ('game_min_player', models.IntegerField(blank=True, default=1)),
                ('game_max_player', models.IntegerField(blank=True, default=1)),
                ('game_image_path', models.CharField(blank=True, default='', max_length=100)),
                ('game_playtime', models.CharField(blank=True, default='', max_length=100)),
                ('game_expansion', models.BooleanField()),
            ],
        ),
    ]
