# Generated by Django 2.2.5 on 2020-06-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardGame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_image_path',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
