# Generated by Django 2.2.5 on 2020-06-16 16:41

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference', models.CharField(blank=True, choices=[('Western', 'Western'), ('Eastern', 'Eastern')], max_length=20)),
                ('team', models.CharField(max_length=30)),
            ],
            managers=[
                ('Schedule', django.db.models.manager.Manager()),
            ],
        ),
    ]
