# Generated by Django 2.2.5 on 2020-06-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasketballApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=60)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
            ],
        ),
    ]
