# Generated by Django 2.2.5 on 2020-06-16 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BasketballApp', '0002_createcontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createcontact',
            name='description',
        ),
        migrations.RemoveField(
            model_name='createcontact',
            name='name',
        ),
    ]
