# Generated by Django 2.2.5 on 2020-06-16 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BasketballApp', '0004_auto_20200616_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='team',
            new_name='teamz',
        ),
    ]
