# Generated by Django 2.2.5 on 2020-06-16 21:36

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('BasketballApp', '0006_auto_20200616_1933'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='createcontact',
            managers=[
                ('CreateContacts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='schedule',
            managers=[
                ('Schedules', django.db.models.manager.Manager()),
            ],
        ),
    ]
