# Generated by Django 2.2.5 on 2020-06-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasketballApp', '0008_auto_20200616_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcontact',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='createcontact',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='createcontact',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
