# Generated by Django 2.2.5 on 2020-06-10 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RefereeName', models.CharField(max_length=100)),
                ('RefereeKind', models.CharField(max_length=100)),
                ('RefereeAddress', models.CharField(max_length=100)),
                ('RefereeEmailAddress', models.CharField(max_length=100)),
                ('RefereePhoneNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeamName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SoccerMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MatchAddress', models.CharField(max_length=100)),
                ('MatchDate', models.DateField()),
                ('MatchTime', models.TimeField()),
                ('RefereeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SoccerApp.Referees')),
                ('Team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team_1', to='SoccerApp.Team')),
                ('Team_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team_2', to='SoccerApp.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlayerName', models.CharField(max_length=100)),
                ('PlayerAddress', models.CharField(max_length=100)),
                ('PlayerEmailAddress', models.CharField(max_length=100)),
                ('PlayerPhoneNumber', models.IntegerField()),
                ('TeamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SoccerApp.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Coaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CoachName', models.CharField(max_length=100)),
                ('CoachAddress', models.CharField(max_length=100)),
                ('CoachEmailAddress', models.CharField(max_length=100)),
                ('CoachPhoneNumber', models.IntegerField()),
                ('TeamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SoccerApp.Team')),
            ],
        ),
    ]
