# Generated by Django 2.2.5 on 2020-06-12 19:37

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('SoccerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='coaches',
            managers=[
                ('coachOB', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='team',
            managers=[
                ('teamOB', django.db.models.manager.Manager()),
            ],
        ),
    ]
