# Generated by Django 2.2.5 on 2020-05-20 15:23

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeClosetForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('size', models.DecimalField(decimal_places=1, default=0.0, max_digits=100)),
            ],
            managers=[
                ('Shoes', django.db.models.manager.Manager()),
            ],
        ),
    ]
