# Generated by Django 2.2.5 on 2020-05-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoeCloset', '0002_auto_20200520_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoeclosetmodel',
            name='notes',
            field=models.TextField(default='Description', max_length=150),
        ),
        migrations.AlterField(
            model_name='shoeclosetmodel',
            name='brand',
            field=models.CharField(choices=[('Adidas', 'Adidas'), ('Puma', 'Puma'), ('Nike', 'Nike'), ('Gucci', 'Gucci'), ('Michael Kors', 'Michael Kors')], default='blank', max_length=30),
        ),
        migrations.AlterField(
            model_name='shoeclosetmodel',
            name='color',
            field=models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Navy', 'Navy'), ('Brown', 'Brown'), ('Oxblood', 'Oxblood'), ('Other', 'Other')], default='blank', max_length=30),
        ),
    ]
