# Generated by Django 2.2.5 on 2020-05-26 19:53

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comedies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comedy', models.CharField(blank=True, max_length=100)),
                ('actor', models.CharField(blank=True, max_length=100)),
                ('director', models.CharField(blank=True, max_length=100)),
                ('year', models.CharField(blank=True, max_length=100)),
                ('imdb_rating', models.CharField(max_length=100, null=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('review', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            managers=[
                ('Comedies', django.db.models.manager.Manager()),
            ],
        ),
    ]
