# Generated by Django 2.2.5 on 2020-06-02 19:33

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DarkRoom', models.CharField(max_length=30)),
                ('PhotoBooth', models.CharField(max_length=30)),
                ('PolaroidInstant', models.CharField(choices=[('Fashion', 'Portrait'), ('Street', 'Landscape'), ('Wildlife', 'Astrophotography'), ('travel', 'Wedding'), ('Documentary', 'Marco'), ('Still Life', 'Food'), ('Sports', 'Fine-Art,'), ('Underwater', 'Event'), ('Aerial', 'Abstract'), ('Architectural', 'Candid'), ('Long Exposure', 'Night'), ('Lifestyle', 'Black and White'), ('Stock', 'Infrared')], max_length=30)),
                ('Digital', models.CharField(max_length=30)),
                ('PhotographicFilm', models.CharField(max_length=15)),
            ],
            managers=[
                ('Photography', django.db.models.manager.Manager()),
            ],
        ),
    ]
