# Generated by Django 2.2.5 on 2020-06-16 16:36

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('SpendUsApp', '0006_auto_20200616_0908'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='expense',
            managers=[
                ('Expenses', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('fuel', 'fuel'), ('supplies', 'supplies'), ('drink', 'drink'), ('hotel', 'hotel'), ('food', 'food')], max_length=60),
        ),
    ]
