# Generated by Django 2.2.5 on 2020-06-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpendUsApp', '0007_auto_20200616_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('drink', 'drink'), ('supplies', 'supplies'), ('hotel', 'hotel'), ('food', 'food'), ('fuel', 'fuel')], max_length=60),
        ),
    ]
