# Generated by Django 2.2.5 on 2020-06-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpendUsApp', '0008_auto_20200616_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('drink', 'drink'), ('supplies', 'supplies'), ('food', 'food'), ('hotel', 'hotel'), ('fuel', 'fuel')], max_length=60),
        ),
    ]
