# Generated by Django 2.2.5 on 2020-06-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpendUsApp', '0009_auto_20200616_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('food', 'food'), ('supplies', 'supplies'), ('hotel', 'hotel'), ('drink', 'drink'), ('fuel', 'fuel')], max_length=60),
        ),
    ]
