# Generated by Django 2.2.5 on 2020-06-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpendUsApp', '0011_auto_20200616_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('fuel', 'fuel'), ('food', 'food'), ('drink', 'drink'), ('hotel', 'hotel'), ('supplies', 'supplies')], max_length=60),
        ),
    ]
