# Generated by Django 2.2.5 on 2020-06-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpendUsApp', '0012_auto_20200616_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='image',
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, default='Description of purchase', max_length=300),
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(blank=True, default='Purchaser Name', max_length=60),
        ),
    ]
