# Generated by Django 2.2.5 on 2020-06-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpendUsApp', '0013_auto_20200616_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, default='description of purchase...', max_length=300),
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(blank=True, default='first and last name of purchaser...', max_length=60),
        ),
    ]
