# Generated by Django 2.2.5 on 2020-05-20 19:44

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('Difficulty', models.CharField(choices=[('easy', 'easy'), ('moderate', 'moderate'), ('hard', 'hard')], max_length=10)),
                ('amountCompleted', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('rating', models.DecimalField(choices=[(1, 1), (1.5, 1.5), (2, 2), (2.5, 2.5), (3, 3), (3.5, 3.5), (4, 4), (4.5, 4.5), (5, 5)], decimal_places=1, max_digits=2)),
            ],
            managers=[
                ('hikes', django.db.models.manager.Manager()),
            ],
        ),
    ]
