# Generated by Django 2.2.5 on 2020-05-20 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HikingApp', '0003_auto_20200520_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hikes',
            old_name='StartTime',
            new_name='EndTime',
        ),
        migrations.RemoveField(
            model_name='hikes',
            name='Date',
        ),
        migrations.AddField(
            model_name='hikes',
            name='DateStart',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
