# Generated by Django 2.2.5 on 2020-05-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HikingApp', '0006_auto_20200521_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hikes',
            name='EndTime',
            field=models.TimeField(default=1590085336.8909152),
        ),
    ]
