# Generated by Django 2.2.5 on 2020-05-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HikingApp', '0007_auto_20200521_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hikes',
            name='EndTime',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
