# Generated by Django 2.2.5 on 2020-05-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HikingApp', '0009_auto_20200521_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hikes',
            name='EndTime',
        ),
        migrations.RemoveField(
            model_name='hikes',
            name='StartTime',
        ),
        migrations.AddField(
            model_name='hikes',
            name='End_Time',
            field=models.TimeField(blank=True, default='18:00', null=True),
        ),
        migrations.AddField(
            model_name='hikes',
            name='Start_Time',
            field=models.TimeField(blank=True, default='12:00', null=True),
        ),
        migrations.AlterField(
            model_name='hikes',
            name='Date',
            field=models.DateField(default=None),
        ),
    ]
