# Generated by Django 2.2.5 on 2020-05-21 21:34

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('HikingApp', '0010_auto_20200521_1426'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='hikes',
            managers=[
                ('Hikes', django.db.models.manager.Manager()),
            ],
        ),
    ]
