# Generated by Django 2.2.5 on 2020-05-25 18:55

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('Rap', 'Rap'), ('Pop', 'Pop'), ('Rock', 'Rock'), ('Jazz', 'Jazz'), ('Other', 'Other')], max_length=20)),
                ('NewsOutlets', models.CharField(choices=[('Billboard', 'Billboard'), ('Fuse', 'Fuse'), ('SPIN', 'SPIN'), ('Digital Music News', 'Digital Music News')], max_length=50)),
            ],
            managers=[
                ('MNews', django.db.models.manager.Manager()),
            ],
        ),
    ]
