# Generated by Django 2.2.5 on 2020-06-17 21:15

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Player_Name', models.CharField(max_length=30)),
                ('Character_Name', models.CharField(max_length=20)),
                ('Race', models.CharField(choices=[('Android', 'Android'), ('Human', 'Human'), ('Kasatha', 'Kasatha'), ('Lashunta', 'Lashunta'), ('Shirren', 'Shirren'), ('Vesk', 'Vesk')], max_length=20)),
                ('HP', models.IntegerField(default=0, max_length=20)),
                ('Theme', models.CharField(choices=[('Ace Pilot', 'Ace Pilot'), ('Bounty Hunter', 'Bounty Hunter'), ('Icon', 'Icon'), ('Mercenary', 'Mercenary'), ('Outlaw', 'Outlaw'), ('Priest', 'Priest'), ('Scholar', 'Scholar'), ('Spacefarer', 'Spacefarer'), ('Themeless', 'Themeless'), ('Xenoseeker', 'Xenoseeker')], max_length=20)),
                ('Class', models.CharField(choices=[('Envoy', 'Envoy'), ('Mechanic', 'Mechanic'), ('Mystic', 'Mystic'), ('Operative', 'Operative'), ('Solarian', 'Solarian'), ('Soldier', 'Soldier'), ('Technomancer', 'Technomancer')], max_length=20)),
                ('Level', models.IntegerField(default=0, max_length=20)),
                ('Size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=20)),
                ('Senses', models.CharField(blank=True, max_length=20)),
                ('Speed', models.IntegerField(default=0, max_length=20)),
                ('Gender', models.CharField(blank=True, max_length=20)),
                ('Home_World', models.CharField(blank=True, max_length=20)),
                ('Alignment', models.CharField(choices=[('Lawful Good', 'Lawful Good'), ('Neutral Good', 'Neutral Good'), ('Chaotic Good', 'Chaotic Good'), ('Lawful Neutral', 'Lawful Neutral'), ('Neutral', 'Neutral'), ('Chaotic Neutral', 'Chaotic Neutral'), ('Lawful Evil', 'Lawful Evil'), ('Neutral Evil', 'Neutral Evil'), ('Chaotic Evil', 'Chaotic Evil')], max_length=20)),
                ('Deity', models.CharField(blank=True, max_length=20)),
                ('Languages', models.CharField(blank=True, max_length=20)),
            ],
            managers=[
                ('Character', django.db.models.manager.Manager()),
            ],
        ),
    ]
