# Generated by Django 2.2.5 on 2020-06-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFToons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='HP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='Level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='Speed',
            field=models.IntegerField(default=0),
        ),
    ]
